
home = ENV['HOME']
VM_WEB_PORT = 8080

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: VM_WEB_PORT, host: 8080

#   config.vm.synced_folder "src/", "/srv/website"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "256"
  end

#   config.vm.provision "ansible" do |ansible|
#     ansible.playbook = "site.yaml"
#     ansible.extra_vars = {
#       :nginx_http_default_server_port => VM_WEB_PORT
#     }
#   end
end
