Vagrant.configure("2") do |config|

  config.vm.define "web" do |web|
    web.vm.box = "centos/stream8"
    web.vm.box_version = "20210210.0"
  end

  config.vm.define "server" do |server|
    server.vm.box = "debian/stretch64"
  end
end
